spring:
  application:
    name: report-service

server:
  port: 8092
  servlet:
    context-path: /reporting

# Api Documentation
springdoc:
  api-docs:
    path: /api-docs
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
