{
 "title": "Go and PostgreSQL Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "GC Duration Seconds",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "singlestat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Memory Allocation (bytes)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Total Allocated Memory",
   "type": "singlestat",
   "gridPos": { "x": 12, "y": 3, "w": 6, "h": 3 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes_total" }
   ]
  },
  {
   "title": "Heap Allocation (in use)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes" }
   ]
  },
  {
   "title": "Number of Heap Objects",
   "type": "singlestat",
   "gridPos": { "x": 12, "y": 6, "w": 6, "h": 3 },
   "targets": [
    { "expr": "go_memstats_heap_objects" }
   ]
  },
  {
   "title": "PostgreSQL Scrape Duration (seconds)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds"
    }
   ]
  },
  {
   "title": "PostgreSQL Scrape Errors",
   "type": "singlestat",
   "gridPos": { "x": 12, "y": 9, "w": 6, "h": 3 },
   "targets": [
    { "expr": "pg_exporter_last_scrape_error" }
   ]
  }
 ]
}