version: '3'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=technow
      - POSTGRES_USER=technow
      - POSTGRES_PASSWORD=technow

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://technow:technow@postgres:5432/technow?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - minionetwork

  minio:
    image: bitnami/minio:2024.2.26
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    expose:
      - "9000"
      - "9001"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/dashboards/sources:/var/lib/grafana/dashboards
    links:
      - prometheus
    networks:
      - minionetwork
    environment:
      - DS_PROMETHEUS=http://prometheus:9090

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - minionetwork
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    # Grafana binding: http://prometheus:9090

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - minionetwork
    # Grafana binding:  http://loki:3100

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    depends_on:
      - loki


  # Kafka
  zookeeper:
    container_name: zookeeper
    restart: always
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    restart: always
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
  grafana_data:
    driver: local
