version: '3'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=technow
      - POSTGRES_USER=technow
      - POSTGRES_PASSWORD=technow
    networks:
      - minionetwork

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://technow:technow@postgres:5432/technow?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - minionetwork

  minio:
    image: bitnami/minio:2024.2.26
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./core/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./core/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./core/provisioning/dashboards/sources:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - minionetwork
    environment:
      - DS_PROMETHEUS=http://prometheus:9090

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - minionetwork
    volumes:
      - ./core/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - minionetwork

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./core/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - minionetwork

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - minionetwork

  server:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma_server
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - minionetwork

#  core:
#    image: core
#    container_name: core
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - zipkin
#    networks:
#      - minionetwork
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/technow
#      - SPRING_DATASOURCE_USERNAME=technow
#      - SPRING_DATASOURCE_PASSWORD=technow

  api_server:
    image: api_server
    container_name: api-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      - minionetwork

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    ports:
      - "8081:8081"
    depends_on:
      - api_server
    networks:
      - minionetwork

#  reports_service:
#    image: reports_service
#    container_name: reports_service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - api_server
#    networks:
#      - minionetwork
#
  notification_service:
    image: notification_service
    container_name: notification_service
    ports:
      - "8083:8083"
    depends_on:
      - api_server
    networks:
      - minionetwork

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
  grafana_data:
    driver: local
  chroma-data:
    driver: local
