# Database
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  # Jpa
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: none
  # Enable virtual threads
  threads:
    virtual:
      enabled: true

# Cors
custom:
  frontend:
    app-url: ${FRONTEND_URL}

# Minio

minio:
  url: ${MINIO_URL}
  access:
    key: ${MINIO_ACCESS_KEY}
  secret:
    key: ${MINIO_SECRET_KEY}



