global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: [ 'minio:9000' ]

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]