spring:
  application:
    name: notification-service

server:
  port: 8091
  servlet:
    context-path: /notification

custom:
  core-url: http://localhost:8080
  remindersSchedulerTime: 5000

# Api Documentation
springdoc:
  api-docs:
    path: /api-docs
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

