spring:
  application:
    name: notification-service

server:
  port: 8091
  servlet:
    context-path: /notification

custom:
  core-url: http://core:8080
  remindersSchedulerTime: 5000

# Api Documentation
springdoc:
  api-docs:
    path: /api-docs
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://api-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
